markdown: rdiscount
permalink: /:title/
url: http://fuqssi.com
#highlighter: pygments
pygments: true
name: 南柯一梦
description: You know my loneliness is only kept for you, my sweet songs are only sung for you.
author: vincen
email: vincen.gao@gmail.com
duoshuo: vincen_gao
hub: vincen
safe: true
paginate: 100
about: "形相清癯，丰姿隽爽，萧疏轩举，湛然若神..."
